### ISSUE TITLE
Not able to compile it.

### ISSUE THREAD

**Issue by t4nec** [csabigee/shell-rc#1]
Hello, 
I have tried to compile it by my self, but was not able to do it on both Linux and Windows, as it cannot find Qwidget directory. Is it possible to provide me with an exe of the program ?Thank you in advance!

**Comment by cshegedus-dsp** [comment]
Hello!
I will send you an installer in a few days.

**Comment by csabigee** [comment]
Hello!
I will send you an installer in a few days.

**Comment by csabigee** [comment]
Hello!
Here is the link for the windows x64 installer:
[https://drive.google.com/file/d/16c5UyQQHvu-Hr1ywa6I8n9Ah5otda881/view?usp=sharing](https://drive.google.com/file/d/16c5UyQQHvu-Hr1ywa6I8n9Ah5otda881/view?usp=sharing)

**Comment by csabigee** [comment]
I updated the toolchain to Qt_6_5_3_MSVC2019
There is a new installer with new models:
https://drive.google.com/file/d/16c5UyQQHvu-Hr1ywa6I8n9Ah5otda881/view?usp=sharing
