### ISSUE TITLE
New Car Compile

### ISSUE THREAD

**Issue by inanc-zz** [csabigee/shell-rc#2]
Can you upload the compilation of the code of the new model vehicles for Windows?

**Comment by csabigee** [comment]
I made some tweaks:
The keyboard WASD, and arrow keys act like 2 separate control devices
I updated the toolchain to Qt_6_5_3_MSVC2019
https://drive.google.com/file/d/16c5UyQQHvu-Hr1ywa6I8n9Ah5otda881/view?usp=sharing
